### PR TITLE
Fix wrong documentation telling driftctl needs write access to S3 state files

### PR DESCRIPTION
**Pull request by bertux**
| Q                 | A
| ----------------- | ---
| 🐛 Bug fix?       | no
| 🚀 New feature?   | no
| ⚠ Deprecations?   | no
| ❌ BC Break       | no
| 🔗 Related issues | #105
| ❓ Documentation  | yes 

## Description

Just documentation update to fix the issue after testing it successfully locally.

### CODE REVIEW

**Review by eliecharra — APPROVED** [review]
Thanks a lot for this catch 👌🏻

**Comment by eliecharra** [comment]
Hmm we have an issue with CircleCI, an option was preventing run on forked PR.

Could you make a small update to trigger a new CI build ? I can merge as it but we need to make it work for future contributions.

**Comment by eliecharra** [comment]
> Could you make a small update to trigger a new CI build ? I can merge as it but we need to make it work for future contributions.

Nevermind about this ☝🏻 , just fixed the CI issue on our side with a test PR.

**Comment by wbeuil** [comment]
@all-contributors please add @bertux for doc

**Pull request merged**
