### PR TITLE
Add all-contributors specification

### PR DESCRIPTION
**Pull request by wbeuil**
| Q                 | A
| ----------------- | ---
| 🐛 Bug fix?       | no
| 🚀 New feature?   | no
| ⚠ Deprecations?   | no
| ❌ BC Break       | no
| 🔗 Related issues | none
| ❓ Documentation  | yes

## Description

All-Contributors specification to thank all the people who have contributed to drifctl !

You can find the usage of the bot [here](https://allcontributors.org/docs/en/bot/usage)

### CODE REVIEW

**Review by eliecharra — APPROVED** [review]

**Comment by wbeuil** [comment]
@all-contributors please add @sjourdan for doc, ideas, talk, question

**Comment by wbeuil** [comment]
@all-contributors please add @eliecharra for doc, code, bug, review, maintenance, test, infra

**Comment by wbeuil** [comment]
@all-contributors please add @moadibfr for doc, code, bug, review, maintenance, test

**Comment by wbeuil** [comment]
@all-contributors please add @wbeuil for doc, code, bug, review, maintenance, test, tool

**Comment by wbeuil** [comment]
@all-contributors please add @emahe22 for doc, ideas, business, fundingFinding

**Comment by wbeuil** [comment]
@all-contributors please add @GeraldC13 for doc, ideas, business, content

**Pull request merged**
