### PR TITLE
Replace manual terraform execution with hashicorp/terraform-exec

### PR DESCRIPTION
**Pull request by sshota0809**
| Q                 | A
| ----------------- | ---
| 🐛 Bug fix?       | no
| 🚀 New feature?   | no
| ⚠ Deprecations?   | no
| ❌ BC Break       | no
| 🔗 Related issues | #119
| ❓ Documentation  | no

## Description

I'm done with replacing manual terraform execution with hashicorp/terraform-exec
Please review my commits!

### CODE REVIEW

**Review by eliecharra — COMMENTED** [review]
That look awesome, nothing to say 👍🏻 

I tried locally and it seems that terraform apply errors are displayed twice, could you investigate ?

image

**Comment by eliecharra** [comment]
Hmm it seems to be an issue with my IDE (Goland), when running test with `make acc` it seems I don't have any issues

image

**Comment by sshota0809** [comment]
@eliecharra 
It seems wired. Should I investigate about it more?

**Comment by eliecharra** [comment]
> @eliecharra
> It seems wired. Should I investigate about it more?

let me rather investigate this on my side.

I'll keep you informed

**Review by eliecharra — APPROVED** [review]

**Pull request merged**
