### PR TITLE
Issue - 1616 - run NewAwsNatGatewayEipAssoc after NewAwsNatGatewayEip…

### PR DESCRIPTION
**Pull request by n2N8Z**
…Assoc, and remove eip associations from remoteResources and resourcesFromState

| Q                 | A
| ----------------- | ---
| 🐛 Bug fix?       | yes
| 🚀 New feature?   | no
| ⚠ Deprecations?   |no
| ❌ BC Break       | no
| 🔗 Related issues | #1616
| ❓ Documentation  | no

## Description
run NewAwsNatGatewayEipAssoc after NewAwsNatGatewayEipAssoc, and remove eip associations from remoteResources and resourcesFromState

### CODE REVIEW

**Comment by moadibfr** [comment]
hey @n2N8Z 👋 
Thanks a lot for you contribution ! 🙏 
This looks good and should fix the issue you discovered. We need you to sign the cla to be able to merge you contribution.
Also I was thinking maybe adding a test case could have been good

**Comment by n2N8Z** [comment]
Re the CLA, the CLAassistant message says:
```
You have signed the CLA already but the status is still pending? Let us recheck it.
```
What else do I need to do ?

**Comment by moadibfr** [comment]
> Re the CLA, the CLAassistant message says:
> 
> ```
> You have signed the CLA already but the status is still pending? Let us recheck it.
> ```
> 
> What else do I need to do ?

can you click on the icon above that says "not signed yet"

**Comment by n2N8Z** [comment]
Done. Now it's happy.

**Review by moadibfr — APPROVED** [review]
Thanks a lot for this contribution 🙏

**Comment by moadibfr** [comment]
@all-contributors please add @n2N8Z for bug

**Pull request merged**
