### PR TITLE
Embed the environment variables before PreExec in ACC test

### LINKED ISSUE #175: Acceptance Test for AWS instance failed when AWS Region is not us-east-1 in my AWS profile
Hello everyone!

**Description**

I tried to execute Acceptance Test for AWS instance with following command.

```
ACC_AWS_PROFILE=individual AWS_PROFILE=individual-read-only DRIFTCTL_ACC=true go test -run=TestAcc_ ./pkg/resource/aws/aws_instance_test.go
```

* `individual` is IAM User attached `AdministratorAccess` policy.
* `individual-read-only` is IAM User attached `ReadOnlyAccess` policy
* Region for above IAM User is defined as `ap-northeast-1` in `~/.aws/config`

But, above test have failed with following error.

```
...
--- FAIL: TestAcc_AwsInstance_WithBlockDevices (119.42s)
    aws_instance_test.go:59: Error, unexpected number of instances found, manual check required
FAIL
FAIL  command-line-arguments    120.458s
FAIL
```

**Environment**

 - OS: 
```
ProductName:	Mac OS X
ProductVersion:	10.15.2
```
 - driftctl version: Using main branch (HEAD = `78f1e40acc43e76dfd27173027870bc217c88e8e`)
- Go: 1.15.5 darwin/amd64

**How to reproduce**

Region for your IAM User is defined as `ap-northeast-1` in `~/.aws/config` (Precisely other than `us-east-1`)

**Possible Solution**

I investigated the reason this error occurs and finally found it. In following Terraform file, region is defined as `us-east-1`

https://github.com/cloudskiff/driftctl/blob/78f1e40acc43e76dfd27173027870bc217c88e8e/pkg/resource/aws/testdata/acc/aws_instance/providers.tf#L1-L3

And the environment variable `"AWS_REGION": "us-east-1"` is also defined in following file.

https://github.com/cloudskiff/driftctl/blob/78f1e40acc43e76dfd27173027870bc217c88e8e/pkg/resource/aws/aws_instance_test.go#L34-L41

On the other hand, the environment variable defined in `acceptance.AccCheck` is embedded as following file.

https://github.com/cloudskiff/driftctl/blob/78f1e40acc43e76dfd27173027870bc217c88e8e/test/acceptance/testing.go#L274-L283

It means `PreExec` is executed before the environment is embedded, so `aws ec2 describe-instances` in `PreExec` for Acceptance Test for AWS instance is executed specifying region as the one in `~/.aws/config`

https://github.com/cloudskiff/driftctl/blob/78f1e40acc43e76dfd27173027870bc217c88e8e/pkg/resource/aws/aws_instance_test.go#L39-L54

I think the environment variables should be embedded before `PreExec`, so above conditions should be swapped as following.

```
 if len(check.Env) > 0 { 
 	for key, value := range check.Env { 
 		os.Setenv(key, value) 
 	} 
 } 
 if check.PreExec != nil { 
 	c.useTerraformEnv() 
 	check.PreExec() 
 	c.restoreEnv() 
 } 
```

Actually I modified source and confirmed the test passed! This modification makes Acceptance Test more friendly to every developer all over the world!

If needed, I create PR about this issue :smiley:

**Additional context**
none.

Thanks a lot for reading my issue :smiley_cat:

### PR DESCRIPTION
**Pull request by sshota0809**
| Q                 | A
| ----------------- | ---
| 🐛 Bug fix?       | yes
| 🚀 New feature?   | no
| ⚠ Deprecations?   | no
| ❌ BC Break       | no
| 🔗 Related issues | #175
| ❓ Documentation  | no

## Description
I fixed #175.
Please review my commit!

### CODE REVIEW

**Review by eliecharra — APPROVED** [review]
LGTM, thanks a lot @sshota0809 🎉

**Comment by eliecharra** [comment]
@sshota0809 Could you remove your fork of driftctl from circleCI ? It prevent our CircleCI check to run on your PR.

**Comment by sshota0809** [comment]
@eliecharra 

I checked the document you give me, and according to the document,

```
Note: If a user submits a pull request to your repository from a fork, but no pipeline is triggered, then the user most likely is following a project fork on their personal account rather than the project itself of CircleCi, causing the jobs to trigger under the user’s personal account and not the organization account.
To resolve this issue, have the user unfollow their fork of the project on CircleCI and instead follow the source project.
This will trigger their jobs to run under the organization when they submit pull requests.
```

But I didn't follow my fork of driftctl on circleCI.

This screen shot is the list of projects.
スクリーンショット 2021-02-01 19 47 48

What should I do? I'm so sorry I'm not familiar with circleCI :cry:

**Comment by eliecharra** [comment]
What a weird behavior from CircleCI ... Can you try to follow our project in circle from this page https://app.circleci.com/projects/project-dashboard/github/cloudskiff/ ?

Then try to update this PR by rebasing it on main

**Comment by eliecharra** [comment]
@wbeuil Maybe we could open a support ticket for this ?

**Comment by wbeuil** [comment]
> @wbeuil Maybe we could open a support ticket for this ?

I will open a ticket on their side then

**Comment by sshota0809** [comment]
@eliecharra @wbeuil 
Thanks for your help!

This URL seems 404...
https://app.circleci.com/projects/project-dashboard/github/cloudskiff/

スクリーンショット 2021-02-01 20 00 57

**Comment by eliecharra** [comment]
@sshota0809 We just opened a support ticket on CircleCI.

Thanks for trying to fix this but we don't want you to spend too much time on it. We'll keep you informed when we get some update from Circle 😉

**Comment by eliecharra** [comment]
Merging since we do not have any response from CircleCI, I've updated the PR onto main to trigger test but this is a weird workaround.

Thanks a lot for your work @sshota0809

**Comment by sshota0809** [comment]
@eliecharra 
Thank you for merging.
I would like to contribute this awesome tool more, so I have to solve this wired issue😢

**Comment by wbeuil** [comment]
Thanks @sshota0809 for your contribution ! No worry we're gonna find what's blocking. We're still waiting for a response from CircleCI. We'll keep you posted !

**Comment by wbeuil** [comment]
@sshota0809, CircleCI just came back to us saying that you are following your own forked project and not the main project. 

Can you double check that you are not following your forked project in CircleCI, but the cloudskiff/driftctl project?

**Comment by sshota0809** [comment]
@wbeuil 
Thank you for reply.
I have checked that I don't follow my own forked repository for sure. I have an idea now that I will try to delete my own forked repository once, and fork origin repository again.

And after that, if you don't mind I would like to push PR to origin repository as a test to confirm if circleCI test is kicked correctly. Is that ok?

**Comment by wbeuil** [comment]
Sure @sshota0809 let's try that !

**Comment by sshota0809** [comment]
@wbeuil 
I have confirmed that CircleCI test was kicked correctly from my new forked repository. Thanks a lot for your support!

**Pull request merged**
